### ISSUE TITLE
Jquery blocked in https

### ISSUE THREAD

**Issue by Ezerbeth** [atmoner/php-pastebin-v3#44]
Hello,

Figured I'd point out that Firefox blocks mix-mode content now, so that the login javascript menu does not work if your site is on https. Simply replace the link in index.php from http://code.jquery.com... to https://code.jquery.com...

This should probably be default even if not on https.

Thanks for the awesome pastebin!

**Comment by link0ln** [comment]
mkdir ./js
cd ./js
wget https://code.jquery.com/jquery-2.1.3.min.js -O jq.js
Fixing by edit index.php
$hook->addJs('Jquery','https://<host>/js/jq.js','','1');
