### ISSUE TITLE
unable to install and connect db

### ISSUE THREAD

**Issue by iamrohan14** [atmoner/php-pastebin-v3#55]
Fatal error: Uncaught Error: Call to undefined function mysql_connect() in C:\xampp\htdocs\paste\install.php:171 Stack trace: #0 {main} thrown in C:\xampp\htdocs\paste\install.php on line 171

**Comment by gj12** [comment]
php7 dropped the mysql.so support you need to modify the code to support mysqli or pdo_mysql
