### ISSUE TITLE
Can't paste a backslash

### ISSUE THREAD

**Issue by jonathanballs** [atmoner/php-pastebin-v3#9]
When entering a piece of text is entered for pasting, all backslashes are removed.

This is quite annoying but also hints at some kind of security flaw although I didn't explore further. The backslash thing definitely has to change. Would love to help out but I'm v. inexperienced in PHP.
# INPUT TEXT

this\ contains\ backslashes
# PASTEBIN OUTPUT

this contains backslashes

**Comment by gmask** [comment]
I am currently facing this issue and the linked website is down. How do I enable backslashes surviving without having to escape them every time?
